### ISSUE TITLE
Warning: file_get_contents(modules/contrib/formblock/formblock.js): failed to open stream: No such file or directory in backdrop_build_js_cache() (line 5212 of /home/backdrop/repo/www/core/includes/common.inc).

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/formblock#1]
I get the following error when visiting a content type page and saving:

> Warning: file_get_contents(modules/contrib/formblock/formblock.js): failed to open stream: No such file or directory in backdrop_build_js_cache() (line 5212 of /home/backdrop/repo/www/core/includes/common.inc).

It looks like this is because formblock.module is trying to use `#attached` on the old path of the JS file:

``` php
      '#attached' => array(
        'js' => array(backdrop_get_path('module', 'formblock') . '/formblock.js'),
      ),
```

The JS file is now under a `js/` directory.

**Comment by serundeputy** [comment]
hrmm ... @quicksketch seems like the path is correct here: https://github.com/backdrop-contrib/formblock/commit/7966c0abc2fa78706ae2f1238f73ed2096cf82fa

Is that the wrong place? That is the only instance of a call to formblock.js that I saw in the codebase.

~Geoff

**Comment by quicksketch** [comment]
Ah, sure enough. Running an older version. Thanks @serundeputy!
